services:
  demo-queue:
    container_name: demo-queue
    image: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
  demo-leader:
    container_name: demo-leader
    build: 
      context: ./src
      dockerfile: leader/Dockerfile
    environment:
     - PYTHONUNBUFFERED=1  # for logging to show
  demo-worker:
    container_name: demo-worker
    build: 
      context: ./src
      dockerfile: worker/Dockerfile
    depends_on:
      - demo-queue
    environment:
     - PYTHONUNBUFFERED=1  # for logging to show
    # deploy:
    #   replicas: 1
  demo-db:
    container_name: demo-db
    build: 
      context: ./src
      dockerfile: db/Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pw
